line_length:
  warning: 120
  error: 150
disabled_rules:
  - variable_name
  - force_cast
  - force_try
  - function_body_length
  - syntactic_sugar
  - shorthand_operator
included:
  - Yomu
  - YomuTests
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - R.generated.swift
  - YomuTests/Utils/JSONFileReader.swift
  - Yomu/Common/Utils/Function.swift
